services:
  postgres:
    image: postgres:17
    container_name: bigdata_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./mock_data:/mock_data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - bigdata-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: bigdata_ch
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=clickhouse_db
    ports:
      - '8123:8123'
      - '9000:9000'
    healthcheck:
      test: [ 'CMD', 'clickhouse-client', '--query', 'SELECT 1' ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bigdata-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdata_jp
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/opt/spark/jars:ro
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - bigdata-network


networks:
  bigdata-network:
    driver: bridge